// <auto-generated />
using System;
using MedAuditoriosPesquisa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedAuditoriosPesquisa.Migrations
{
    [DbContext(typeof(MedAuditoriosPesquisaContext))]
    [Migration("20231221140425_SeedingInicial")]
    partial class SeedingInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedAuditoriosPesquisa.Models.Filial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Filial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Belo Horizonte (MG)"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "São Paulo (SP)"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rio de Janeiro (RJ)"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Salvador (BA)"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Porto Alegre (RS)"
                        });
                });

            modelBuilder.Entity("MedAuditoriosPesquisa.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailContato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilialId")
                        .HasColumnType("int");

                    b.Property<string>("LinkVisita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("NomeContato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeDireito")
                        .HasColumnType("int");

                    b.Property<int>("StatusPrimarioId")
                        .HasColumnType("int");

                    b.Property<int>("StatusSecundarioId")
                        .HasColumnType("int");

                    b.Property<int>("TelefoneContato")
                        .HasColumnType("int");

                    b.Property<int>("TipoCadeira")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.HasIndex("StatusPrimarioId");

                    b.HasIndex("StatusSecundarioId");

                    b.ToTable("Local");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 400,
                            DataInteracao = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailContato = "jorge@jorge.com.br",
                            FilialId = 1,
                            LinkVisita = "https://trello.com/",
                            Nome = "Colégio CRA",
                            NomeContato = "Jorge",
                            Observacao = "Ótimo local",
                            PeDireito = 5,
                            StatusPrimarioId = 1,
                            StatusSecundarioId = 1,
                            TelefoneContato = 21,
                            TipoCadeira = 2,
                            UrlImagem = "https://conceitos.com/wp-content/uploads/cultura/Auditorio.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 200,
                            DataInteracao = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailContato = "laura@laura.com.br",
                            FilialId = 2,
                            LinkVisita = "https://trello.com/",
                            Nome = "Hotel Golden Tulip",
                            NomeContato = "Laura",
                            Observacao = "Péssimo local",
                            PeDireito = 4,
                            StatusPrimarioId = 2,
                            StatusSecundarioId = 2,
                            TelefoneContato = 21,
                            TipoCadeira = 3,
                            UrlImagem = "https://www.proacustica.org.br/assets/images/Publicacoes/Cases/AuditorioCNC_001.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = 350,
                            DataInteracao = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailContato = "antônio@antônio.com.br",
                            FilialId = 3,
                            LinkVisita = "https://trello.com/",
                            Nome = "Colégio Batista",
                            NomeContato = "Antônio",
                            Observacao = "Achei feio.",
                            PeDireito = 5,
                            StatusPrimarioId = 3,
                            StatusSecundarioId = 3,
                            TelefoneContato = 251,
                            TipoCadeira = 2,
                            UrlImagem = "https://www.univates.br/eventos//media/alugue/auditorios/aud_7_01.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Capacidade = 700,
                            DataInteracao = new DateTime(2023, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailContato = "malaquias@malaquias.com.br",
                            FilialId = 4,
                            LinkVisita = "https://trello.com/",
                            Nome = "Teatro Morumbi",
                            NomeContato = "Malaquias",
                            Observacao = "Perfeito. Aprovado pra tudo.",
                            PeDireito = 8,
                            StatusPrimarioId = 4,
                            StatusSecundarioId = 4,
                            TelefoneContato = 21,
                            TipoCadeira = 0,
                            UrlImagem = "https://ama-al.com.br/wp-content/uploads/2021/09/MK36029-2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Capacidade = 200,
                            DataInteracao = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailContato = "ramses@silva.com.br",
                            FilialId = 5,
                            LinkVisita = "https://trello.com/",
                            Nome = "Cinema Carioca",
                            NomeContato = "Ramses",
                            Observacao = "Ótimo local",
                            PeDireito = 3,
                            StatusPrimarioId = 5,
                            StatusSecundarioId = 5,
                            TelefoneContato = 21,
                            TipoCadeira = 2,
                            UrlImagem = "https://images.adsttc.com/media/images/5f7d/feb4/63c0/1772/3f00/0340/slideshow/Marcus_Wend_3.jpg?1602092715"
                        });
                });

            modelBuilder.Entity("MedAuditoriosPesquisa.Models.StatusPrimario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusPrimario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Aguardando Retorno do Local"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Aguardando Visita"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Aprovado sem Restrições"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Aprovado com Restrições"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Backup"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Banco de Dados"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Lista restrita"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Contato Sem Sucesso"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Local Atual"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Local Potencial"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Não Aluga"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Não Existe na Cidade"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Não Possui Auditório"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Reprovado"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Sem Contato"
                        });
                });

            modelBuilder.Entity("MedAuditoriosPesquisa.Models.StatusSecundario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusSecundario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Reprovado Capacidade"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Acessibilidade"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Capacidade"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Infraestrutura"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Localização / Segurança"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Não Atende"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Ocupado"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Responsável Não Está"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Telefone Errado / FAX"
                        });
                });

            modelBuilder.Entity("MedAuditoriosPesquisa.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Funcao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "daniel.armond@rmedcursosmedicos.com.br",
                            Funcao = 2,
                            Nome = "Daniel Armond",
                            Senha = "root"
                        },
                        new
                        {
                            Id = 2,
                            Email = "aline.inojosa@rmedcursosmedicos.com.br",
                            Funcao = 1,
                            Nome = "Aline Inojosa",
                            Senha = "medaline123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "joao.gomes@rmedcursosmedicos.com.br",
                            Funcao = 0,
                            Nome = "João Gomes",
                            Senha = "medjoao123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "michele.bhering@rmedcursosmedicos.com.br",
                            Funcao = 1,
                            Nome = "Michele Bhering",
                            Senha = "medmichele123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "alana.nascimento@rmedcursosmedicos.com.br",
                            Funcao = 1,
                            Nome = "Alana Nascimento",
                            Senha = "medalana123"
                        });
                });

            modelBuilder.Entity("MedAuditoriosPesquisa.Models.Local", b =>
                {
                    b.HasOne("MedAuditoriosPesquisa.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedAuditoriosPesquisa.Models.StatusPrimario", "StatusPrimario")
                        .WithMany()
                        .HasForeignKey("StatusPrimarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedAuditoriosPesquisa.Models.StatusSecundario", "StatusSecundario")
                        .WithMany()
                        .HasForeignKey("StatusSecundarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");

                    b.Navigation("StatusPrimario");

                    b.Navigation("StatusSecundario");
                });
#pragma warning restore 612, 618
        }
    }
}
